Added optionnal prop "is-centered" to Navbar component
buefy/buefy pull request #2825
Opened 2020-08-28 10:17 UTC by holtolee

Hello already did a small fix in documentation but this is my very first PR to realy improve buefy, so let me know if i am doing it right or not.

Fixes #2646

## Proposed Changes

-Added "is-centered" optionnal prop to Navbar instead of adding a center slot
-Added corresponding prop in navbar documentation
-Added a _navbar.scss file

2020-08-29 02:12 UTC, febrihidayan commented
@holtolee It's amazing, I've been waiting a long time for this 👏

2020-08-29 06:04 UTC, jtommy commented
@holtolee Well done!
Can you add a wrapper class b-navbar and apply your style under it ?

2020-08-31 07:54 UTC, jtommy requested changes

2020-08-31 07:54 UTC, jtommy commented on docs/pages/components/navbar/api/navbar.js
> +            name: '<code>is-centered</code>',
Please rename it to `centered`

2020-08-31 11:19 UTC, merged