Fixes #2678: Override is-boxed display style in NavbarDropdown
buefy/buefy pull request #3027
Opened 2020-11-07 12:23 UTC by yuchaosydney

Fixes #2678

## Proposed Changes

- Override class `is-boxed` `display` style to `display: none` as default in NavbarDropdown
- When "box" style dropdown is opened, its div `<div class="navbar-dropdown is-boxed"></div>` will be styled as `display:block` by `.navbar-item.is-active .navbar-dropdown` as shown in following screenshot (Therefore, this issue can be resolved by neither tweaking existing transition style nor making new vue transition logic):

<img width="270" alt="Screen Shot 2020-11-07 at 11 16 13 pm" src="https://user-images.githubusercontent.com/5698884/98440906-b489e100-214f-11eb-9760-f69205ed24ba.png">

2020-11-07 19:50 UTC, service-paradis requested changes
Thanks for this PR.
This solution solved the tabbing issue. Unfortunately, we lose the fading effect without using transition.

2020-11-07 19:50 UTC, service-paradis commented on src/components/navbar/NavbarDropdown.vue
> +</style>
Thanks for this PR. I will need to make some tests.
Can you please add this code in `scss/components/_navbar.scss` instead? Buefy do not use scoped styles.

2020-11-07 21:08 UTC, yuchaosydney commented
> using

2020-11-07 21:08 UTC, yuchaosydney commented
> Thanks for this PR.
> This solution solved the tabbing issue. Unfortunately, we lose the fading effect without using transition.

Thanks for pointing out. I will make a change to use transition

2020-11-08 13:10 UTC, yuchaosydney commented on src/scss/components/_navbar.scss
> +        visibility: hidden;
Hi @service-paradis ,

There is actually a cleaner solution: although `transition-property` does not work with `display`, it works with `visibility`. And `visibility: hidden` disables tab event as well.

Therefore, I put `visibility: hidden` as default for `.navbar-dropdown.is-boxed`, and when dropdown is open `.navbar-item.has-dropdown.is-active`, set to `visibility: visible;`.

2020-11-08 18:54 UTC, service-paradis approved these changes
LGTM 💯 
Thanks for your help!

2020-11-08 19:31 UTC, merged