Fix #3056 - Reset time on carousel when clicking arrow
buefy/buefy pull request #3057
Opened 2020-11-24 03:48 UTC by harryJst

Fixes #3056 

## Proposed Changes
- Add and call a `resetTimer` method to reset the timer when the carousel index is changed by clicking on the arrow

2020-11-24 07:10 UTC, jtommy commented
@Tofandel can you take a look?

2020-11-24 08:06 UTC, Tofandel commented
@harryJst there is some small issues in this PR, you're missing a check on the timer before clear interval, you should also use the startTimer method right after that

You also should use the changeActive method to call the reset timer and not next and prev
```
if (newIndex !== this.value) {
       this.$emit('input', newIndex)
}

Right after the emit 
```

2020-11-24 12:28 UTC, harryJst commented
Thanks for your feedback, much appreciated!
I have a two questions to clarify the change, only learning JS;
I see what you mean, but wouldn't expected behaviour be that the carousel would continue playing after a click not pause?
If I put it in change active won't it have unintended consequences in the other parts of the code where `changeActive` is called?

2020-11-24 12:35 UTC, Tofandel commented
@harryJst It would continue, the pause actually doesn't work as you would expect, it is actually stopping the timer and when unstopping resetting it, so effectively restarting the timer is pause + restart, if you look you will see the pause has the exact same code at the exception of the `this.pause = true` but you'll also see that when you restart the timer you have `this.pause = false`

> If I put it in change active won't it have unintended consequences in the other parts of the code where changeActive is called?

Correct, that's exactly the point since next and prev will change the value, so will a v-model change but you'd want the behavior to be the same, that is the timer to be reset

2020-11-26 09:44 UTC, Tofandel requested changes
You misunderstood my comment re the pause timer, you shouldn't delete the restartTimer method rather just make it
```
restartTimer() {
  this.pauseTimer();
  this.startTimer();
} 
```

2020-11-26 19:21 UTC, harryJst commented
Hey @Tofandel, thanks for you time to review this. Seems like you've spent too much time on such a tiny PR, so sorry about that!

2020-11-26 19:53 UTC, Tofandel approved these changes
All good now

2020-11-26 20:06 UTC, merged