Fix: Expired and broken websites in expo page (#3802)
buefy/buefy pull request #3856
Opened 2023-05-15 07:22 UTC by amal-qb

Fixes #3802 

## Proposed Changes

- Fixes #3802

The close button is similar to Modal's close button.

![image](https://github.com/buefy/buefy/assets/122610766/1363627b-c4f8-4ae2-8089-efbe513c907c)

2023-08-08 09:35 UTC, amal-qb commented
@wesdevpro Can you please review this PR?

2023-08-08 19:01 UTC, wesdevpro commented
> @wesdevpro Can you please review this PR?

I can do that 😅

2023-08-08 19:11 UTC, wesdevpro requested changes

2023-08-08 19:11 UTC, wesdevpro commented on src/components/sidebar/Sidebar.vue
> +                if (this.isOpen && this.fullwidth) this.cancel('outside')
Please put `this.cancel('outside')` on a new line underneath your last IF statement

2023-08-08 19:11 UTC, wesdevpro commented on src/scss/components/_sidebar.scss
Looks good 🎉

2023-08-12 14:08 UTC, wesdevpro approved these changes

2023-08-14 13:43 UTC, wesdevpro commented
@amal-qb can you also add documentation for this?

2023-08-22 03:50 UTC, amal-qb commented
@wesdevpro I have added documentation.

2023-08-22 15:08 UTC, merged