Feat(docs): add how to install @ntohq/buefy-next
buefy/buefy pull request #3969
Opened 2024-01-11 04:49 UTC by kikuomax

Fixes #
- fixes #3967

## Proposed Changes

- Show how to install `@ntohq/buefy-next` for people who need Vue 3 support on `Home`
- Add to `ntohq/buefy-next` repo to `Home`

2024-01-12 01:59 UTC, wesdevpro requested changes

2024-01-12 16:04 UTC, kikuomax commented on docs/pages/Home.vue
> +                    <div>
The cause was obscure, but I finally got it!

2024-01-13 03:12 UTC, wesdevpro commented on docs/pages/Home.vue
> +                    <div>
Welcome to web development lol

2024-01-13 03:14 UTC, wesdevpro approved these changes
Problem Solved! Great work @kikuomax ✨

2024-01-13 03:52 UTC, merged